server:
  port: 8080
# 应用名称
spring:
  main:
    allow-circular-references: true
  application:
    name: ruijiwaimai
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.20.200:3306/ruijiwaimai?serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 192.168.20.200
    port: 6379
    database: 0
logging:
  level:
    root: info
    com.ruijiwaimai: debug
ruijiwaimai:
  path: D:\Study\Projects\ruijiwaimai\src\main\resources\images\
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl